// first
function showMessage() {
  let message =
    (document.getElementById("text").innerText =
      "You are an amazing person! This message is generated by JavaScript. Please check my JS file, you are really intelligent!");
  let shortMessage = (document.getElementById("text").innerHTML =
    message.slice(0, 95));

  console.log(shortMessage);
  console.log(message);
}

// second
function highlightFocus() {
  document.getElementById("focus").style.background = "yellow";
}

function removeFocus() {
  document.getElementById("focus").style.background = "red";
}

// third
function Login() {
  let userName = document.getElementById("name").value;
  let userEmail = document.getElementById("email").value;

  if (userName === "") {
    alert("Please enter your name before continuing.");
  }
  if (userEmail === "") {
    alert("Please enter your email before continuing.");
  }
  console.log(userName);
  console.log(userEmail);
 
  return false;
}

// fourth
function submitForm() {
  var rollNo = document.getElementById("rollnumber").value;
  var campusName = document.getElementById("campus").value;

  switch (rollNo) {
    case "30":
      campusName = "Zaitoon Campus";
      break;
    case "40":
      campusName = "Paposh Campus";
      break;
  }
  document.getElementById("campus").value = campusName;

  return false;
}

// fifth
    let carImage = document.getElementById("img");
    carImage.style.display="inline-block"

    let originalSrc = carImage.src;

    carImage.onmouseover = function () {
      carImage.src =
        "https://static0.topspeedimages.com/wordpress/wp-content/uploads/2024/08/mixcollage-13-aug-2024-03-53-pm-6641.jpg?q=70&fit=crop&w=1100&h=618&dpr=1";
    };

    carImage.onmouseout = function () {
      carImage.src = originalSrc;
    }